# Generated by Django 6.0.4 on 2026-04-19 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('crop_type', models.CharField(max_length=255)),
                ('planting_date', models.DateField()),
                ('current_stage', models.CharField(choices=[('Planted', 'Planted'), ('Growing', 'Growing'), ('Ready', 'Ready'), ('Harvested', 'Harvested')], default='Planted', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_fields', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
