# Generated by Django 6.0.4 on 2026-04-19 06:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['-created_at'], 'verbose_name': 'Field', 'verbose_name_plural': 'Fields'},
        ),
        migrations.AddField(
            model_name='field',
            name='area_hectares',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Field area in hectares', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='field',
            name='expected_harvest_date',
            field=models.DateField(blank=True, help_text='Target harvest date (used for risk calculations)', null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='location',
            field=models.CharField(blank=True, default='', help_text="GPS coordinates or descriptive location (e.g. 'North Paddock, Nakuru')", max_length=255),
        ),
        migrations.AddField(
            model_name='field',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_fields', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='field',
            name='crop_type',
            field=models.CharField(help_text='Type of crop e.g. Maize, Wheat', max_length=100),
        ),
        migrations.AlterField(
            model_name='field',
            name='current_stage',
            field=models.CharField(choices=[('Planted', 'Planted'), ('Growing', 'Growing'), ('Flowering', 'Flowering'), ('Ready', 'Ready for Harvest'), ('Harvested', 'Harvested')], default='Planted', max_length=20),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(help_text='Field name or identifier', max_length=255),
        ),
        migrations.AlterField(
            model_name='field',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Field observations and notes'),
        ),
        migrations.AlterField(
            model_name='field',
            name='planting_date',
            field=models.DateField(help_text='Date the crop was planted'),
        ),
    ]
