services:
  - type: web
    name: shamba-records-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.14
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
    autoDeploy: false
